# Generated by Django 5.2.7 on 2025-11-04 01:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clients_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(help_text="When the timer started"),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, help_text="When the timer stopped", null=True
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=0, help_text="Duration in minutes"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of work done", null=True
                    ),
                ),
                (
                    "task_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the specific task",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "Running"),
                            ("PAUSED", "Paused"),
                            ("STOPPED", "Stopped"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="STOPPED",
                        help_text="Current status of the time log",
                        max_length=20,
                    ),
                ),
                (
                    "is_billable",
                    models.BooleanField(
                        default=True, help_text="Whether this time is billable"
                    ),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Hourly rate for billing",
                        max_digits=8,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_logs",
                        to="clients_app.client",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Time Log",
                "verbose_name_plural": "Time Logs",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="TimeLogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(help_text="Start time of this entry"),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, help_text="End time of this entry", null=True
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=0, help_text="Duration in minutes"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Notes for this entry", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "time_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="time_logs_app.timelog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Time Log Entry",
                "verbose_name_plural": "Time Log Entries",
                "ordering": ["start_time"],
            },
        ),
        migrations.AddIndex(
            model_name="timelog",
            index=models.Index(
                fields=["user", "-start_time"], name="time_logs_a_user_id_b7e333_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timelog",
            index=models.Index(
                fields=["client", "-start_time"], name="time_logs_a_client__ebf17e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timelog",
            index=models.Index(fields=["status"], name="time_logs_a_status_6ef80c_idx"),
        ),
    ]
