# Generated by Django 5.2.7 on 2025-11-20 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients_app", "0001_initial"),
        ("projects_app", "0005_alter_projecttask_title_usergoals"),
        ("time_logs_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="timelog",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="time_logs",
                to="projects_app.project",
            ),
        ),
        migrations.AddField(
            model_name="timelog",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="time_logs",
                to="projects_app.projecttask",
            ),
        ),
        migrations.AddIndex(
            model_name="timelog",
            index=models.Index(
                fields=["project", "-start_time"], name="time_logs_a_project_19cd4f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timelog",
            index=models.Index(
                fields=["task", "-start_time"], name="time_logs_a_task_id_c6b1a4_idx"
            ),
        ),
    ]
