# Generated by Django 5.2.7 on 2025-11-20 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects_app", "0006_project_inquiry"),
        ("time_logs_app", "0002_timelog_project_timelog_task_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="timelog",
            name="milestone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="time_logs",
                to="projects_app.projectmilestone",
            ),
        ),
    ]
