# Generated by Django 5.2.7 on 2025-11-03 21:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Client full name", max_length=100),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True, help_text="Company name", max_length=100, null=True
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        help_text="Primary contact email", max_length=254
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Contact phone number",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True, help_text="Billing address", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="ACTIVE",
                        help_text="Client status",
                        max_length=20,
                    ),
                ),
                (
                    "total_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total revenue from this client",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "outstanding_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Current outstanding balance",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes about the client",
                        null=True,
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, help_text="Client website", null=True),
                ),
                (
                    "industry",
                    models.CharField(
                        blank=True,
                        help_text="Industry/sector",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "secondary_email",
                    models.EmailField(
                        blank=True,
                        help_text="Secondary contact email",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "secondary_phone",
                    models.CharField(
                        blank=True,
                        help_text="Secondary phone number",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "tax_id",
                    models.CharField(
                        blank=True,
                        help_text="Tax ID or VAT number",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "payment_terms",
                    models.CharField(
                        default="Net 30",
                        help_text="Payment terms (e.g., Net 30, Net 15)",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clients_app_clients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClientContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Contact person's name", max_length=100),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, help_text="Job title", max_length=100, null=True
                    ),
                ),
                ("email", models.EmailField(help_text="Contact email", max_length=254)),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Contact phone", max_length=20, null=True
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Is this the primary contact?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="clients_app.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Contact",
                "verbose_name_plural": "Client Contacts",
                "ordering": ["-is_primary", "name"],
            },
        ),
        migrations.CreateModel(
            name="ClientNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note_type",
                    models.CharField(
                        choices=[
                            ("GENERAL", "General Note"),
                            ("MEETING", "Meeting Notes"),
                            ("CALL", "Phone Call"),
                            ("EMAIL", "Email Communication"),
                            ("FOLLOW_UP", "Follow-up Required"),
                        ],
                        default="GENERAL",
                        help_text="Type of note",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(help_text="Note title", max_length=200)),
                ("content", models.TextField(help_text="Note content")),
                (
                    "follow_up_required",
                    models.BooleanField(
                        default=False, help_text="Does this require follow-up?"
                    ),
                ),
                (
                    "follow_up_date",
                    models.DateField(blank=True, help_text="Follow-up date", null=True),
                ),
                (
                    "follow_up_completed",
                    models.BooleanField(
                        default=False, help_text="Has follow-up been completed?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_notes",
                        to="clients_app.client",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who created the note",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Note",
                "verbose_name_plural": "Client Notes",
                "ordering": ["-created_at"],
            },
        ),
    ]
