# Generated by Django 5.2.7 on 2025-11-20 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients_app", "0001_initial"),
        ("inquiries", "0002_alter_inquiry_budget_range_alter_inquiry_timeline"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientnote",
            name="inquiry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="client_notes",
                to="inquiries.inquiry",
            ),
        ),
    ]
