# Generated by Django 5.2.7 on 2025-11-20 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_dashboard", "0001_initial"),
        ("clients_app", "0001_initial"),
        ("inquiries", "0002_alter_inquiry_budget_range_alter_inquiry_timeline"),
        ("invoices_app", "0002_auto_20251119_1005"),
        ("projects_app", "0005_alter_projecttask_title_usergoals"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemlog",
            name="related_client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="system_logs",
                to="clients_app.client",
            ),
        ),
        migrations.AddField(
            model_name="systemlog",
            name="related_inquiry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="system_logs",
                to="inquiries.inquiry",
            ),
        ),
        migrations.AddField(
            model_name="systemlog",
            name="related_invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="system_logs",
                to="invoices_app.invoice",
            ),
        ),
        migrations.AddField(
            model_name="systemlog",
            name="related_project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="system_logs",
                to="projects_app.project",
            ),
        ),
    ]
