# Generated by Django 5.2.7 on 2025-11-04 02:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clients_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Project title", max_length=200)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Project description", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNING", "Planning"),
                            ("IN_PROGRESS", "In Progress"),
                            ("ON_HOLD", "On Hold"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PLANNING",
                        help_text="Project status",
                        max_length=20,
                    ),
                ),
                (
                    "project_phase",
                    models.CharField(
                        choices=[
                            ("DISCOVERY", "Discovery"),
                            ("DESIGN", "Design"),
                            ("DEVELOPMENT", "Development"),
                            ("TESTING", "Testing"),
                            ("DEPLOYMENT", "Deployment"),
                            ("MAINTENANCE", "Maintenance"),
                        ],
                        default="DISCOVERY",
                        help_text="Current project phase",
                        max_length=20,
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Project budget",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Hourly billing rate",
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, help_text="Project start date", null=True
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, help_text="Project end date", null=True
                    ),
                ),
                (
                    "estimated_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Estimated total hours",
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "design_tools",
                    models.JSONField(
                        blank=True, default=list, help_text="Design tools used"
                    ),
                ),
                (
                    "technologies",
                    models.JSONField(
                        blank=True, default=list, help_text="Technologies used"
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        default="MEDIUM",
                        help_text="Project priority",
                        max_length=20,
                    ),
                ),
                (
                    "progress_percentage",
                    models.IntegerField(
                        default=0,
                        help_text="Project completion percentage (0-100)",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is project currently active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        help_text="Associated client",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="clients_app.client",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects_app_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("DESIGN", "Design File"),
                            ("DOCUMENT", "Document"),
                            ("CODE", "Code/Script"),
                            ("IMAGE", "Image"),
                            ("VIDEO", "Video"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        help_text="Type of file",
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="File title/description", max_length=200
                    ),
                ),
                (
                    "file_name",
                    models.CharField(help_text="Original file name", max_length=255),
                ),
                (
                    "file_path",
                    models.CharField(help_text="File path/URL", max_length=500),
                ),
                ("file_size", models.IntegerField(help_text="File size in bytes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="projects_app.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who uploaded the file",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Project File",
                "verbose_name_plural": "Project Files",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Milestone title", max_length=200),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Milestone description", null=True
                    ),
                ),
                ("due_date", models.DateField(help_text="Milestone due date")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("OVERDUE", "Overdue"),
                        ],
                        default="PENDING",
                        help_text="Milestone status",
                        max_length=20,
                    ),
                ),
                ("order", models.IntegerField(default=0, help_text="Display order")),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False, help_text="Is milestone completed"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="projects_app.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Milestone",
                "verbose_name_plural": "Project Milestones",
                "ordering": ["order", "due_date"],
            },
        ),
        migrations.CreateModel(
            name="ProjectNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note_type",
                    models.CharField(
                        choices=[
                            ("GENERAL", "General Note"),
                            ("MEETING", "Meeting Notes"),
                            ("CLIENT_FEEDBACK", "Client Feedback"),
                            ("TECHNICAL", "Technical Note"),
                            ("ISSUE", "Issue/Problem"),
                            ("SOLUTION", "Solution/Update"),
                        ],
                        default="GENERAL",
                        help_text="Type of note",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(help_text="Note title", max_length=200)),
                ("content", models.TextField(help_text="Note content")),
                (
                    "is_internal",
                    models.BooleanField(
                        default=True,
                        help_text="Is this internal note (not visible to client)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="projects_app.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who created the note",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Note",
                "verbose_name_plural": "Project Notes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Task title", max_length=200)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Task description", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TODO", "To Do"),
                            ("IN_PROGRESS", "In Progress"),
                            ("REVIEW", "In Review"),
                            ("COMPLETED", "Completed"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="TODO",
                        help_text="Task status",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        default="MEDIUM",
                        help_text="Task priority",
                        max_length=20,
                    ),
                ),
                (
                    "assigned_to",
                    models.CharField(
                        blank=True,
                        help_text="Person assigned to task",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "estimated_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Estimated hours for task",
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("order", models.IntegerField(default=0, help_text="Display order")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "milestone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="projects_app.projectmilestone",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="projects_app.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Task",
                "verbose_name_plural": "Project Tasks",
                "ordering": ["order", "created_at"],
            },
        ),
    ]
