# Generated by Django 5.2.7 on 2025-11-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="case_study",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Structured case study content",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="client_type",
            field=models.CharField(
                blank=True,
                help_text="Client type shown in portfolio (e.g. SME, Startup)",
                max_length=120,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="industry",
            field=models.CharField(
                blank=True,
                help_text="Industry label for the project",
                max_length=120,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="intro",
            field=models.TextField(
                blank=True,
                help_text="Short intro used on portfolio listings",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="logo",
            field=models.CharField(
                blank=True,
                help_text="URL to project logo or avatar",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="slug",
            field=models.SlugField(
                blank=True, help_text="URL-friendly slug", max_length=200, null=True
            ),
        ),
    ]
