# Generated by Django 5.2.7 on 2025-11-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects_app", "0002_project_case_study_project_client_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={},
        ),
        migrations.RemoveField(
            model_name="projecttask",
            name="title",
        ),
        migrations.AddField(
            model_name="projecttask",
            name="name",
            field=models.CharField(default="", help_text="Task name", max_length=200),
        ),
        migrations.AlterField(
            model_name="projecttask",
            name="status",
            field=models.CharField(
                choices=[
                    ("TODO", "To Do"),
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                    ("BLOCKED", "Blocked"),
                ],
                default="TODO",
                help_text="Task status",
                max_length=20,
            ),
        ),
    ]
