# Generated by Django 5.2.7 on 2025-11-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "projects_app",
            "0003_alter_project_options_remove_projecttask_title_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projecttask",
            name="name",
        ),
        migrations.AddField(
            model_name="projecttask",
            name="title",
            field=models.CharField(default="", help_text="Task title", max_length=200),
        ),
    ]
