# Generated by Django 5.2.7 on 2025-11-20 09:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects_app", "0004_remove_projecttask_name_projecttask_title"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="projecttask",
            name="title",
            field=models.CharField(help_text="Task title", max_length=200),
        ),
        migrations.CreateModel(
            name="UserGoals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monthly_revenue_target",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Monthly revenue target in dollars",
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "client_satisfaction_target",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Target client satisfaction rating (1-5)",
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "current_client_satisfaction",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Current average client satisfaction rating",
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Goals",
                "verbose_name_plural": "User Goals",
            },
        ),
    ]
