# Generated by Django 5.2.7 on 2025-11-20 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inquiries", "0003_inquiry_converted_client"),
        ("projects_app", "0005_alter_projecttask_title_usergoals"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="inquiry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_projects",
                to="inquiries.inquiry",
            ),
        ),
    ]
