# Generated by Django 5.2.7 on 2025-11-03 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_name",
                    models.CharField(
                        help_text="Name of the person making the inquiry.",
                        max_length=150,
                    ),
                ),
                ("client_email", models.EmailField(max_length=254)),
                (
                    "client_phone",
                    models.CharField(
                        blank=True,
                        help_text="Phone number for follow-up",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "client_company",
                    models.CharField(
                        blank=True,
                        help_text="Company/organization name",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("message", models.TextField(help_text="Client's inquiry message")),
                (
                    "service_requested",
                    models.CharField(
                        choices=[
                            ("WEB_DEV", "Web Development"),
                            ("WEB_DESIGN", "Web Design"),
                            ("MOBILE_APP", "Mobile App Development"),
                            ("BRANDING", "Branding & Logo Design"),
                            ("UI_UX", "UI/UX Design"),
                            ("SEO", "SEO & Digital Marketing"),
                            ("CONSULTING", "Technical Consulting"),
                            ("MAINTENANCE", "Website Maintenance"),
                            ("OTHER", "Other Services"),
                        ],
                        default="OTHER",
                        max_length=15,
                    ),
                ),
                (
                    "budget_range",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("UNDER_1K", "Under $1,000"),
                            ("1K_5K", "$1,000 - $5,000"),
                            ("5K_10K", "$5,000 - $10,000"),
                            ("10K_25K", "$10,000 - $25,000"),
                            ("25K_50K", "$25,000 - $50,000"),
                            ("OVER_50K", "Over $50,000"),
                            ("DISCUSS", "To be discussed"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "timeline",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ASAP", "ASAP"),
                            ("1_WEEK", "Within 1 week"),
                            ("2_WEEKS", "Within 2 weeks"),
                            ("1_MONTH", "Within 1 month"),
                            ("3_MONTHS", "Within 3 months"),
                            ("FLEXIBLE", "Flexible timeline"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("HIGH", "High Priority"),
                            ("MEDIUM", "Medium Priority"),
                            ("LOW", "Low Priority"),
                        ],
                        default="MEDIUM",
                        max_length=6,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New Inquiry"),
                            ("CONTACTED", "Contacted Client"),
                            ("QUOTED", "Quote Sent"),
                            ("NEGOTIATING", "Negotiating"),
                            ("WON", "Project Won"),
                            ("LOST", "Project Lost"),
                            ("ON_HOLD", "On Hold"),
                        ],
                        default="NEW",
                        max_length=12,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes and follow-up details",
                        null=True,
                    ),
                ),
                (
                    "follow_up_date",
                    models.DateField(
                        blank=True, help_text="Next follow-up date", null=True
                    ),
                ),
                (
                    "reminder_sent",
                    models.BooleanField(
                        default=False,
                        help_text="Whether follow-up reminder has been sent",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        default=list, help_text="List of tags for organizing inquiries"
                    ),
                ),
                (
                    "lead_score",
                    models.IntegerField(
                        default=0, help_text="Calculated lead score (0-100)"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("WEBSITE", "Website Contact Form"),
                            ("EMAIL", "Direct Email"),
                            ("LINKEDIN", "LinkedIn"),
                            ("UPWORK", "Upwork/Freelance Platform"),
                            ("REFERRAL", "Referral"),
                            ("SOCIAL", "Social Media"),
                            ("OTHER", "Other"),
                        ],
                        default="WEBSITE",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Inquiries",
                "ordering": ["-created_at"],
            },
        ),
    ]
