# Generated by Django 5.2.7 on 2025-11-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inquiries", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inquiry",
            name="budget_range",
            field=models.CharField(
                blank=True,
                choices=[
                    ("UNDER_1K", "Under $1,000"),
                    ("SMALL_1K_5K", "$1,000 - $5,000"),
                    ("MID_5K_10K", "$5,000 - $10,000"),
                    ("MID_10K_25K", "$10,000 - $25,000"),
                    ("LARGE_25K_50K", "$25,000 - $50,000"),
                    ("OVER_50K", "Over $50,000"),
                    ("DISCUSS", "To be discussed"),
                ],
                max_length=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="timeline",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ASAP", "ASAP"),
                    ("WEEK_ONE", "Within 1 week"),
                    ("WEEKS_TWO", "Within 2 weeks"),
                    ("MONTH_ONE", "Within 1 month"),
                    ("MONTHS_THREE", "Within 3 months"),
                    ("FLEXIBLE", "Flexible timeline"),
                ],
                max_length=15,
                null=True,
            ),
        ),
    ]
