# Generated by Django 5.2.7 on 2025-11-19 10:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("invoices_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='InvoiceProject',
        ),
    ]
