# Generated by Django 5.2.7 on 2025-11-20 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients_app", "0002_clientnote_inquiry"),
        ("invoices_app", "0002_auto_20251119_1005"),
        ("time_logs_app", "0003_timelog_milestone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="clients_app.client",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceproject",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoice_projects",
                to="clients_app.client",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="billed_time_logs",
            field=models.ManyToManyField(
                blank=True,
                help_text="Time logs included in this invoice",
                related_name="invoices",
                to="time_logs_app.timelog",
            ),
        ),
        migrations.DeleteModel(
            name="Client",
        ),
    ]
