# Generated by Django 5.2.7 on 2025-10-28 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("company", models.CharField(blank=True, max_length=200)),
                ("message", models.TextField()),
                ("project_type", models.CharField(blank=True, max_length=100)),
                ("budget_range", models.CharField(blank=True, max_length=100)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Project name", max_length=200)),
                (
                    "slug",
                    models.SlugField(help_text="URL-friendly identifier", unique=True),
                ),
                (
                    "client_type",
                    models.CharField(
                        help_text="Type of client (SME, Startup, etc.)", max_length=100
                    ),
                ),
                (
                    "industry",
                    models.CharField(help_text="Industry sector", max_length=100),
                ),
                ("intro", models.TextField(help_text="Brief project introduction")),
                ("logo", models.URLField(help_text="Logo image URL")),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("design", "Design Project"),
                            ("development", "Development Project"),
                            ("fullstack", "Full-Stack Project"),
                        ],
                        default="development",
                        help_text="Type of project",
                        max_length=20,
                    ),
                ),
                (
                    "design_tools",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of design tools used (e.g., ['figma', 'photoshop'])",
                    ),
                ),
                (
                    "starting_point",
                    models.TextField(help_text="Problem/challenge description"),
                ),
                (
                    "the_transformation",
                    models.TextField(help_text="Solution/approach description"),
                ),
                (
                    "journey_end",
                    models.TextField(help_text="Results/outcomes description"),
                ),
                (
                    "visuals",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Dictionary of visual assets with URLs",
                    ),
                ),
                (
                    "deliverables",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of deliverables for design projects",
                    ),
                ),
                (
                    "design_system",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Design system information (colors, typography, etc.)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether project is publicly visible"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Display order"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Image title/description", max_length=200
                    ),
                ),
                ("image_url", models.URLField(help_text="Image URL")),
                (
                    "alt_text",
                    models.CharField(
                        help_text="Alt text for accessibility", max_length=200
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Display order"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
