# Generated by Django 5.2.7 on 2025-10-28 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactsubmission",
            options={"ordering": ["-submitted_at"]},
        ),
        migrations.AddField(
            model_name="contactsubmission",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contactsubmission",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="contactsubmission",
            name="location_name",
            field=models.CharField(
                blank=True,
                help_text="City, Country or location description",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="contactsubmission",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=11, null=True
            ),
        ),
        migrations.CreateModel(
            name="MapMarker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Marker title", max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Optional description"),
                ),
                ("latitude", models.DecimalField(decimal_places=8, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=8, max_digits=11)),
                (
                    "location_name",
                    models.CharField(help_text="City, Country", max_length=200),
                ),
                (
                    "marker_type",
                    models.CharField(
                        choices=[
                            ("client", "Client Location"),
                            ("office", "Office Location"),
                            ("project", "Project Location"),
                            ("event", "Event Location"),
                        ],
                        default="client",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "related_contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="map_markers",
                        to="projects.contactsubmission",
                    ),
                ),
                (
                    "related_project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="map_markers",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "-created_at"],
            },
        ),
    ]
